sfbrigade/intentional-walk-server

home/models/dailywalk.py
home/models/intentionalwalk.py
home/templates/home/base.html
home/templates/home/user_list.html
home/views/web/home.py
home/views/web/intentionalwalk.py
home/views/web/user.py

1. Removed account filtering based on contest enrollment since enrollment is assumed by default. This should simply filter user stats by only the date range.
2. Hotfix to display all distances as miles instead of meters (initial assumption was that the distance unit would be miles)
3. Added link to the contest creation page on navbar.

Fixed contest view & distance unit. Added a link to contest creation admin page on nav

---

home/migrations/0007_new_demographic_cols.py
home/models/__init__.py
home/models/account.py
home/models/race.py
home/views/api/appuser.py
home/views/web/user.py
server/settings.py

Adds columns/fields to Account model:
* `is_sf_resident`: whether the user is an SF resident or not, based on zip code
* `is_latino`: whether the user identifies as being of Latino/Hispanic origin
* `race`: many-to-many self-identified racial groups
* `gender`: self-identified gender identity
* `is_tester`: user is an app tester
- Adds new fields
- Adds migration to add new fields and backfill `is_sf_resident` based on zip
- Adds list (set) of SF zip codes
- Creates new Race model for many-to-many mapping of users to race
- Includes a reversible migration
- Safe to revert but may result in loss of new Account data

New demographic info

---

home/views/web/data.py
home/views/web/user.py

- Add new_signup and active_during_contest fields in Downloaded CSV file
- Revised if-clause to filter out non-users (previous users who were inactive during contest) from downloadable CSV
- Update param to contest_id to enable contest-specific filters
- Safe to revert

Add new and active fields to users table

---

README.md
home/migrations/0006_auto_20200623_2207.py
home/tests/integration/contest/test_current.py
home/tests/integration/views/web/test_data.py
home/tests/unit/views/web/test_data.py
home/utils/__init__.py
home/utils/generators.py
home/views/web/data.py
home/views/web/user.py
poetry.lock
pyproject.toml
requirements.txt

Adds integration tests for `home/views/web/data.py`
* Create integration tests
* Create fake data generators for unit tests
* Removes addition of dummy row from `home/migrations/0006_auto_20200623_2207.py`
* Skips failing test for `test_contest_current`
* Localizes datetimes passed to queries
Should not require migration.
Safe to revert.

Integration tests using faker to synthesize data

---

home/models/contest.py
home/models/dailywalk.py
home/tests/integration/contest/test_current.py
home/tests/integration/dailywalk/test_create.py
home/tests/unit/test_contest.py
home/views/api/dailywalk.py
poetry.lock
pyproject.toml
requirements.txt

Fixes broken test `test_contest_current` in `home/tests/integration/contest/test_current.py`, which was being skipped because of failures.
Also adds unit test for `Contest.active` to supplement integration test.
* Imports freezegun
* Updates integration test `test_contest_current` to use freezegun instead of libfaketime
* Adds unit test `test_active` in home/tests/unit/test_contest.py
* **Updates dailywalk API such that when a daily walk is added, the active contest is looked up and added to the associated Account**
No migrations.
Safe to revert.

Fix skipped test of current contest

---

example.env
home/management/commands/backfill.py
home/management/commands/resetdb.py

Adds a management function for resetting the DB to a clean state. I would say this actually does not increase our risk exposure because in order to run the command, you would need to have the same privileges and access required for destructive actions executed through `dbshell`. I have also added a manual confirmation step so that it would occur by fat-fingering.
Also adds a management function that backfills the `contests` field of `Account` by iterating through all daily walks, finding the relevant contest, and adding it to the account associated with the walk. This could be replaced by a formal sql migration, but I wanted it to be a command line function where the specific contest id or dates could be specified, which would not be possible with a migration.
Adds two management scripts …

Management functions to reset db and backfill account contests

---

README.md
home/tests/integration/appuser/test_create.py
home/tests/integration/appuser/test_update.py
home/views/api/appuser.py

The IW app will be splitting the registration process into a number of steps. At each step, the user will enter information and press "Next", which will trigger an API call with partial registration data.
* This PR modifies AppUserCreateView to allow first a POST request with just name, email, zip, and age and returns account_id. 
* Each subsequent PUT request will now be an account update that requires account_id along with any additional fields. 
* Revises integration tests in test_create, to limit fields to name, email, zip, and age. 
* Revises test_update to echo these changes
* Adds test_update_appuser_demographics to test_update to process ethnicity, gender, and race
* Safe to revert

Processing new registration flow

---

home/templates/home/user_list.html

Update the heatmaps labels as discussed on 08/10 to:
- Total active participants
- Previous active participants
- New active sign-ups
- Median steps

fix: correct heatmap labels

---

home/templates/home/user_list.html

At times when arrays are empty, the existing javascript code
errors out due to Array.prototype.reduce functions called on
empty arrays without an initial value.
In addition, "Median steps" were not parsed properly in the case
where Math.round ended up producing a NaN value; this change
causes the code to fallback to 0 in an untrue case.
Signed-off-by: Kevin Morris <kevr@0cost.org>

fix: default javascript values used in heatmap labels

---

poetry.lock
pyproject.toml

pytest 5.4 is completely incompatible with Python >= 3.10. On my local development machine, I use 3.10. Since this upgrade doesn't hurt anything, but resolves https://stackoverflow.com/questions/69528842/an-error-while-trying-to-execute-tests-on-python-3-10-with-pytest, I think it makes sense to bring in for the project.

[0-0] update(poetry): update pytest to 7.1.3

---

home/templates/home/user_list.html
home/tests/unit/test_user.py
home/views/web/user.py
poetry.lock
pyproject.toml
static/home/main.css
static/home/user_plots.js

This commit includes a javascript function that can generate these types of user account bar graphs. It depends on some new context variables passed by the user web view, which grab the count values needed for these two graphs from the database.
At the current time, these graphs are placed just below the existing graph found when viewing a contest on the Users page. We likely want to change this positioning, but that can be done in a follow-up PR.
Note: The `Total users: 505` text you see is the current tooltip which follows your mouse as you hover over the graphs. My screenshot tool would not capture the mouse pointer, so it just looks like it's sitting there. That tooltip really needs some kind of style put on it, but it is viewable and functional for now for both graphs independently.

[0-1] feat: add user count bar graphs in the contest view

---

.circleci/config.yml
Dockerfile
README.md
bin/init
docker-compose.yml
poetry.lock
pyproject.toml
scripts/dummydata.py

This script can be used by developers to generate some initial
random data into their local Intentional Walk databases.
See `python scripts/dummydata.py --help` for a list of options.
Importing dummy data into a new local postgres database:
$ python scripts/dummydata.py > iw_db.sql
$ createdb iw_db
$ python manage.py migrate
$ psql iw_db < iw_db.sql
[...takes a while]
$ python manage.py createsuperuser
[...]
$ python manage.py runserver
[...server starts]
Signed-off-by: Kevin Morris <kevr@0cost.org>

[1-0] feat: scripts/dummydata.py - a random dummy SQL data generator

---

home/admin.py

Without this, django searches incorrectly in the related account field, causing an exception to be raised when searches are done within the admin interface.
Signed-off-by: Kevin Morris <kevr@0cost.org>

fix: correct search fields for (Device|DailyWalk|IntentionalWalk)Admin

---

.circleci/config.yml
.coveragerc
.gitignore
Makefile
README.md
docker-compose.override.yml
scripts/coverage_html.py

Upgrading to the latest coverage possible (7.2.0) with the latest coveralls didn’t work, so I opted to
Just leave it at the same version, which we can probably upgrade in a future PR.
Adds a development only service, exposed on port 8001 to view a coverage report:
Simplified the command to `make coverage` that will be useful to view during development:
We can now view it through a nice coveralls UI [here](https://coveralls.io/builds/66015825/source?filename=home%2Fviews%2Fweb%2Fintentionalwalk.py), or if during development :
`make coverage` and visiting `http://localhost:8001` 
Here's the current report of our code coverage, looking quite good so far! Haven't looked too deeply into the test cases, but looks promising so far.
```
home/_init_.py	0	0	0	100%
home/admin.py	44	0	0	100% …
```

Coverage/coveralls Issue #158

---

home/tests/integration/views/api/test_admin.py
home/tests/unit/test_utils.py
home/views/api/admin.py
home/views/api/serializers/request_serializers.py
home/views/api/serializers/response_serializers.py
home/views/api/utils.py
poetry.lock
pyproject.toml

This patch modularizes a controller using django's rest serializers, refactoring`GET /api/admin/users` as  example.
Modularizing with serializers has several benefits, that I think could be very useful for us and future maintainers of this repo (they will appreciate it 😀 , and it will **significantly** help with onboarding)
- Code is much cleaner and easier to read. It's much easier to follow and clearly see the query params and the response.
- It provides automatic error messages if the data is invalid.
- It allows us to reuse the same validation logic in multiple views.
- It integrates well with Django REST Framework's other features, like automatic API documentation. We can easily generate swagger docs API
Some cons are much more code, and more indirection, but as the app is small, I …

Modularizing admin api with serializers

---

.circleci/config.yml
poetry.lock

Our poetry version was upgraded from 1.5.1 to 1.8.2 after this [patch](https://github.com/sfbrigade/intentional-walk-server/pull/175/files#diff-f53a023eedfa3fbf2925ec7dc76eecdc954ea94b7e47065393dbad519613dc89). This [patch](https://github.com/sfbrigade/intentional-walk-server/pull/174) introduced a new dependency without updating the `content-hash` field of the poetry lock.
The current version of poetry we are using for CI (1.2.2) silently lets this pass [through](https://github.com/sfbrigade/intentional-walk-server/pull/174).
Upgrading for 1.8.2 prevents invalid `poetry.lock` from passing CI, and invoke `poetry lock --no-update` to correct the content-hash for the lock file.

Poetry CI Upgrade

---

.circleci/config.yml
home/tests/integration/views/api/test_admin.py

Recently, we've been getting some strange >37% code coverage through  [coveralls](https://coveralls.io/jobs/138742056) while running locally we should be having ~88% code coverage.
The reason for this is because `pytest coverage` was actually failing. The error message was hard to find but it was hidden in the `coveralls` report here on [line 228](https://app.circleci.com/pipelines/github/sfbrigade/intentional-walk-server/535/workflows/fde4abc0-5313-41bb-9168-5d686e531d45/jobs/551)
```
)
E           django.db.utils.NotSupportedError: PostgreSQL 12 or later is required (found 11.17).
../.pyenv/versions/3.11.4/lib/python3.11/site-packages/django/db/backends/base/base.py:214: NotSupportedError
```
Coverage reporting doesn't actually error out the CI, so errors fail silently - to fix this we …

Sync CI postgres image version with Docker to support Django 4.X

---

client/src/Api.js

Related to Issue 205:
The frontend client when selecting "contest_id" was sending the contest start and end date into the API.
This causes a 422 as contest_id and start_end_date are mutually exclusive.
Changed the API call so that it doesn't send start/end date when client_id is not null and vice versa.

Fix Histogram api call to have client_id and start_date/end_date send separately

---

client/src/setupProxy.js
docker-compose.override.yml
example.env

Resolve an `ERRCONNREFUSED` when trying to proxy localhost:3000 to localhost:8000.
This was previously okay before but with the Node 17, this is no longer the case. I don't actually recall any Node upgrades.
> Node.js 17+ no longer prefers IPv4 over IPv6 for DNS lookups. E.g. It's not guaranteed that localhost will be resolved to 127.0.0.1 – it might just as well be ::1 (or some other IP address).
If your target server only accepts IPv4 connections, trying to proxy to localhost will fail if resolved to ::1 (IPv6).
Ways to solve it:
Change target: "http://localhost" to target: "http://127.0.0.1" (IPv4).
https://github.com/chimurai/http-proxy-middleware/blob/3aad7521473bcc182ca43fedb783df1efdedfe39/README.md#nodejs-17-econnrefused-issue-with-ipv6-and-localhost-705
We take the first …

Update proxy to target to 127.0.0.1:8000

---

.circleci/config.yml
docker-compose.override.yml

One of the issues we had with CI was that our CI wasn't necessarily in-sync with our actual build.
We saw this issue twice, once with a Django upgrade that no longer worked with postgres v12 and under, (CI was still on 11.XX) and a second time with forgetting to run a `requirements.txt` update after installing with poetry.
We can resolve this and prevent this issue by just _actually_ using our `docker-compose` set up and running full CI on it.
CircleCI already builds for us using custom pre-built images they've provided, but we can just use our builds and have it run [it](https://circleci.com/docs/building-docker-images/). CircleCI base images provide `docker` and `docker-compose`already pre-installed.
I opted to just go for the [machine …

Actually use our Dockerfile for CI

---

client/src/Components/IntensityMap.js

Heat map isn't correctly rendering for when data is 0.
This is because the scale is incorrect (starting at 1 to max of data) which can end up being [1, 0] when data starts.
Correctly fix to [0, 1] at least, and adjust the UI so we can see the borders.
ASANA: https://app.asana.com/0/1201140011812889/1207387759617792/f

fix: heat map issue

---

client/src/Components/Histogram.js
client/src/Home.js
home/tests/unit/test_histogram.py
home/views/api/histogram/serializers.py

Fixes a few issues:
- There's a person who is 20 million years old, so for the end range, just display >60 instead of relying on the upper end.
- clear errors on new request
- remove the error message on "no data found", as it is valid to have no data found within a given date range
old: 
new:

fix: histogram issues for user age

---

client/src/setupProxy.js
server/settings.py

Resolves CSRF issue when logging in to localhost:3000 due to having two admin pages and using a proxy. Fixed by including localhost:3000 as trusted origin in settings.py
Also resolved static CSSs and JS files from loading due to using a proxy. Fixed by including /static/admin path in proxy.

fix: csrf issue and loading static files on localhost:3000 admin page

---

docs/schema.md
home/tests/integration/appuser/test_create.py
home/tests/unit/api/test_appuser.py
home/views/api/appuser.py

11 lines containing all instances of Tester, replaced with 'iwt'

basic search/replace of Tester with iwt, including schema doc

---

docker-compose.yml

NOTE: local devs will need to delete older version of db container prior to installing this newer major version

Upgraded to postgres:14 in docker-compose.yml

---

poetry.lock
pyproject.toml

Updated Django, black, coveralls and faker to latest versions.

Fix the four outstanding python dependabot alerts.
